#include "crypto_primitives.h"
#include "pqscaas_enclave_t.h"   /* generated by edger8r; has ocall_get_time_ms */
#include "sgx_tseal.h"
#include <string.h>
#include <math.h>                /* log, exp, sqrt, cos — available in sgx_tstdc */

/* ============================================================================
 * Lognormal sampler — Box-Muller transform using sgx_read_rand entropy
 * ============================================================================ */

double trusted_sample_lognormal(double mean_ms, double std_ms) {
    if (mean_ms <= 0.0) return 0.0;

    /* Lognormal parameters: mu, sigma of the underlying normal */
    double cv2   = (std_ms / mean_ms) * (std_ms / mean_ms);
    double sigma = sqrt(log(1.0 + cv2));
    double mu    = log(mean_ms) - 0.5 * sigma * sigma;

    /* Box-Muller: two uniform [0,1) values from sgx_read_rand */
    uint64_t r1 = 0, r2 = 0;
    sgx_read_rand((unsigned char *)&r1, sizeof(r1));
    sgx_read_rand((unsigned char *)&r2, sizeof(r2));

    /* Convert to (0,1] — avoid exact zero for log */
    double u1 = ((r1 & 0x000FFFFFFFFFFFFFULL) | 0x0010000000000000ULL)
                / (double)(1ULL << 53);
    double u2 = ((r2 & 0x000FFFFFFFFFFFFFULL) | 0x0010000000000000ULL)
                / (double)(1ULL << 53);

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
    double z = sqrt(-2.0 * log(u1)) * cos(2.0 * M_PI * u2);

    return exp(mu + sigma * z);
}

/* ============================================================================
 * HMAC-SHA256 — manual RFC 2104 using sgx_sha256_msg
 * ============================================================================ */

sgx_status_t trusted_hmac_sha256(
    const uint8_t *key,  uint32_t key_len,
    const uint8_t *msg,  uint32_t msg_len,
    uint8_t mac[32]
) {
    sgx_status_t ret;

    /* If key > 64 bytes, hash it first */
    uint8_t k[64] = {0};
    if (key_len > 64) {
        ret = sgx_sha256_msg(key, key_len, (sgx_sha256_hash_t *)k);
        if (ret != SGX_SUCCESS) return ret;
        key_len = 32;
    } else {
        memcpy(k, key, key_len);
    }

    /* ipad_key = k XOR 0x36, opad_key = k XOR 0x5C */
    uint8_t ipad[64], opad[64];
    for (int i = 0; i < 64; i++) {
        ipad[i] = k[i] ^ 0x36u;
        opad[i] = k[i] ^ 0x5Cu;
    }

    /* inner = SHA256(ipad || msg) */
    uint32_t inner_len = 64 + msg_len;
    uint8_t *inner_buf = (uint8_t *)__builtin_alloca(inner_len);
    memcpy(inner_buf,       ipad, 64);
    memcpy(inner_buf + 64,  msg,  msg_len);
    uint8_t inner[32];
    ret = sgx_sha256_msg(inner_buf, inner_len, (sgx_sha256_hash_t *)inner);
    if (ret != SGX_SUCCESS) return ret;

    /* mac = SHA256(opad || inner) */
    uint8_t outer_buf[64 + 32];
    memcpy(outer_buf,      opad,  64);
    memcpy(outer_buf + 64, inner, 32);
    ret = sgx_sha256_msg(outer_buf, 64 + 32, (sgx_sha256_hash_t *)mac);
    return ret;
}

/* ============================================================================
 * HKDF-SHA256 — RFC 5869, single-block (okm_len ≤ 32)
 * ============================================================================ */

sgx_status_t trusted_hkdf(
    const uint8_t *ikm,  uint32_t ikm_len,
    const uint8_t *salt, uint32_t salt_len,
    const uint8_t *info, uint32_t info_len,
    uint8_t *okm, uint32_t okm_len,
    double *elapsed_ms
) {
    double t0 = trusted_get_time_ms();

    sgx_status_t ret;

    /* Extract: PRK = HMAC-SHA256(salt, IKM) */
    static const uint8_t zero_salt[32] = {0};
    const uint8_t *eff_salt  = (salt && salt_len > 0) ? salt  : zero_salt;
    uint32_t       eff_slen  = (salt && salt_len > 0) ? salt_len : 32;

    uint8_t prk[32];
    ret = trusted_hmac_sha256(eff_salt, eff_slen, ikm, ikm_len, prk);
    if (ret != SGX_SUCCESS) return ret;

    /* Expand: T(1) = HMAC-SHA256(PRK, info || 0x01) */
    uint32_t expand_len = info_len + 1;
    uint8_t *expand_buf = (uint8_t *)__builtin_alloca(expand_len);
    if (info && info_len > 0) memcpy(expand_buf, info, info_len);
    expand_buf[info_len] = 0x01u;

    uint8_t t1[32];
    ret = trusted_hmac_sha256(prk, 32, expand_buf, expand_len, t1);
    if (ret != SGX_SUCCESS) return ret;

    memcpy(okm, t1, okm_len < 32 ? okm_len : 32);

    if (elapsed_ms) *elapsed_ms = trusted_get_time_ms() - t0;
    return SGX_SUCCESS;
}

/* ============================================================================
 * SHA-256 wrapper with timing
 * ============================================================================ */

sgx_status_t trusted_sha256(
    const uint8_t *data, uint32_t len,
    uint8_t digest[32],
    double *elapsed_ms
) {
    double t0 = trusted_get_time_ms();
    sgx_status_t ret = sgx_sha256_msg(data, len, (sgx_sha256_hash_t *)digest);
    if (elapsed_ms) *elapsed_ms = trusted_get_time_ms() - t0;
    return ret;
}

/* ============================================================================
 * Real SGX seal / unseal with timing
 * ============================================================================ */

sgx_status_t trusted_seal(
    const uint8_t *raw, uint32_t raw_len,
    uint8_t *sealed_buf, uint32_t sealed_buf_size,
    uint32_t *sealed_out_size,
    double *elapsed_ms
) {
    uint32_t needed = sgx_calc_sealed_data_size(0, raw_len);
    if (sealed_buf_size < needed) return SGX_ERROR_INVALID_PARAMETER;

    double t0 = trusted_get_time_ms();
    sgx_status_t ret = sgx_seal_data(
        0, nullptr,          /* no additional MAC text */
        raw_len, raw,
        needed, (sgx_sealed_data_t *)sealed_buf
    );
    if (elapsed_ms) *elapsed_ms = trusted_get_time_ms() - t0;
    if (sealed_out_size) *sealed_out_size = (ret == SGX_SUCCESS) ? needed : 0;
    return ret;
}

sgx_status_t trusted_unseal(
    const uint8_t *sealed_buf, uint32_t sealed_buf_size,
    uint8_t *raw_buf, uint32_t *raw_len,
    double *elapsed_ms
) {
    (void)sealed_buf_size;
    double t0 = trusted_get_time_ms();
    uint32_t add_len = 0;
    sgx_status_t ret = sgx_unseal_data(
        (const sgx_sealed_data_t *)sealed_buf,
        nullptr, &add_len,
        raw_buf, raw_len
    );
    if (elapsed_ms) *elapsed_ms = trusted_get_time_ms() - t0;
    return ret;
}

/* ============================================================================
 * Mock PQ operation timing
 * ============================================================================ */

double trusted_mock_ml_kem_keygen() {
    return trusted_sample_lognormal(MOCK_ML_KEM_KEYGEN.mean, MOCK_ML_KEM_KEYGEN.std_dev);
}

double trusted_mock_ml_kem_encap() {
    return trusted_sample_lognormal(MOCK_ML_KEM_ENCAP.mean, MOCK_ML_KEM_ENCAP.std_dev);
}

double trusted_mock_ml_dsa_keygen() {
    return trusted_sample_lognormal(MOCK_ML_DSA_KEYGEN.mean, MOCK_ML_DSA_KEYGEN.std_dev);
}

double trusted_mock_ml_dsa_sign() {
    return trusted_sample_lognormal(MOCK_ML_DSA_SIGN.mean, MOCK_ML_DSA_SIGN.std_dev);
}

/* ============================================================================
 * Wall-clock time via OCALL
 * ============================================================================ */

double trusted_get_time_ms() {
    double ms = 0.0;
    ocall_get_time_ms(&ms);
    return ms;
}
